version: '3.8'

services:
  aethersync-woker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aethersync_daemon
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"